function rootDir = Setup_Paths(include_legacy, rootDirOverride)
% SETUP_PATHS Configures MATLAB search paths for the navigation repository.
% Uses robust script-relative path resolution so scripts execute correctly
% regardless of the current working directory.
%
% Usage:
%   Setup_Paths()                        % Standard active project path setup
%   Setup_Paths(true)                    % Includes legacy Euler/quaternion/utility folders
%   rootDir = Setup_Paths(false, myDir)  % Explicitly anchors paths to myDir

if nargin < 1 || isempty(include_legacy)
    include_legacy = false;
end

% Resolve repository root relative to caller override or this script location
if nargin >= 2 && ~isempty(rootDirOverride)
    rootDir = char(rootDirOverride);
else
    rootDir = fileparts(mfilename('fullpath'));
    if isempty(rootDir)
        rootDir = pwd;
    end
end

% Explicitly define active project directories (excluding .git, .agents, and codegen)
projectDirs = { ...
    'config', ...
    'core', ...
    fullfile('core', 'lie_algebra'), ...
    fullfile('core', 'manifold'), ...
    fullfile('core', 'sigma_points'), ...
    fullfile('core', 'rotation'), ...
    'filters', ...
    fullfile('filters', 'ekf_lie'), ...
    fullfile('filters', 'ukf_lie'), ...
    'runners', ...
    'geodesy', ...
    'metrics', ...
    'visualization', ...
    'build', ...
    fullfile('build', 'mex'), ...
    'inslib', ...
    'data' ...
};

% Add legacy folders if explicitly requested
if include_legacy
    legacyDirs = { ...
        fullfile('inslib', 'legacy', 'filters_euler'), ...
        fullfile('inslib', 'legacy', 'filters_quaternion'), ...
        fullfile('inslib', 'legacy', 'orphaned_utilities'), ...
        fullfile('inslib', 'legacy', 'compat_aliases') ...
    };
    for i = numel(legacyDirs):-1:1
        targetPath = fullfile(rootDir, legacyDirs{i});
        if exist(targetPath, 'dir')
            addpath(targetPath, '-begin');
        end
    end
end

for i = numel(projectDirs):-1:1
    targetPath = fullfile(rootDir, projectDirs{i});
    if exist(targetPath, 'dir')
        addpath(targetPath, '-begin');
    end
end

% Add repository root directory itself at the front of the path
addpath(rootDir, '-begin');

if nargout == 0
    fprintf('Navigation project paths initialized successfully from: %s\n', rootDir);
end
end
