function rootDir = Setup_Paths(include_legacy)
% SETUP_PATHS Configures MATLAB search paths for the navigation repository.
% Uses robust script-relative path resolution so scripts execute correctly
% regardless of the current working directory.
%
% Usage:
%   Setup_Paths()               % Standard active project path setup
%   Setup_Paths(true)           % Includes legacy Euler/quaternion/utility folders
%   rootDir = Setup_Paths(...)  % Returns resolved repository root directory

if nargin < 1
    include_legacy = false;
end

% Resolve repository root relative to this script location
rootDir = fileparts(mfilename('fullpath'));
if isempty(rootDir)
    rootDir = pwd;
end

% Explicitly define active project directories (excluding .git, .agents, and codegen)
projectDirs = { ...
    'config', ...
    'core', ...
    fullfile('core', 'lie_algebra'), ...
    fullfile('core', 'manifold'), ...
    fullfile('core', 'sigma_points'), ...
    fullfile('core', 'rotation'), ...
    'filters', ...
    fullfile('filters', 'ekf_lie'), ...
    fullfile('filters', 'ukf_lie'), ...
    fullfile('filters', 'spukf_lie'), ...
    'runners', ...
    'geodesy', ...
    'metrics', ...
    'visualization', ...
    'build', ...
    fullfile('build', 'mex'), ...
    'inslib', ...
    'data', ...
    'tests' ...
};

for i = 1:numel(projectDirs)
    targetPath = fullfile(rootDir, projectDirs{i});
    if exist(targetPath, 'dir')
        addpath(targetPath);
    end
end

% Add legacy folders if explicitly requested
if include_legacy
    legacyDirs = { ...
        fullfile('inslib', 'legacy', 'filters_euler'), ...
        fullfile('inslib', 'legacy', 'filters_quaternion'), ...
        fullfile('inslib', 'legacy', 'orphaned_utilities'), ...
        fullfile('inslib', 'legacy', 'compat_aliases') ...
    };
    for i = 1:numel(legacyDirs)
        targetPath = fullfile(rootDir, legacyDirs{i});
        if exist(targetPath, 'dir')
            addpath(targetPath);
        end
    end
end

% Add repository root directory itself
addpath(rootDir);

if nargout == 0
    fprintf('Navigation project paths initialized successfully from: %s\n', rootDir);
end
end
