function A = dynamicJacobian_euler(hx,u,g0)
a1=u(1);
a2=u(2);
a3=u(3);
%w1=u(4);
w2=u(5);
w3=u(6);
ba1=hx(10);
ba2=hx(11);
ba3=hx(12);
%bw1=0;
bw2=hx(14);
bw3=hx(15);
phi=hx(1);
theta=hx(2);
psi=hx(3);
A=[[                                            (sin(phi)*sin(theta)*(bw3 - w3))/cos(theta) - (cos(phi)*sin(theta)*(bw2 - w2))/cos(theta), - cos(phi)*(bw3 - w3) - sin(phi)*(bw2 - w2) - (cos(phi)*sin(theta)^2*(bw3 - w3))/cos(theta)^2 - (sin(phi)*sin(theta)^2*(bw2 - w2))/cos(theta)^2,                                                                                                                                                                       0, 0, 0, 0, 0, 0, 0,                    0,                                                  0,                                                  0, -1, -(sin(phi)*sin(theta))/cos(theta), -(cos(phi)*sin(theta))/cos(theta)]
[                                                                                            cos(phi)*(bw3 - w3) + sin(phi)*(bw2 - w2),                                                                                                                                               0,                                                                                                                                                                       0, 0, 0, 0, 0, 0, 0,                    0,                                                  0,                                                  0,  0,                         -cos(phi),                          sin(phi)]
[                                                                  (sin(phi)*(bw3 - w3))/cos(theta) - (cos(phi)*(bw2 - w2))/cos(theta),                                                 - (cos(phi)*sin(theta)*(bw3 - w3))/cos(theta)^2 - (sin(phi)*sin(theta)*(bw2 - w2))/cos(theta)^2,                                                                                                                                                                       0, 0, 0, 0, 0, 0, 0,                    0,                                                  0,                                                  0,  0,              -sin(phi)/cos(theta),              -cos(phi)/cos(theta)]
[- (sin(phi)*sin(psi) + cos(phi)*cos(psi)*sin(theta))*(ba2 - a2*g0) - (cos(phi)*sin(psi) - cos(psi)*sin(phi)*sin(theta))*(ba3 - a3*g0),                     cos(psi)*sin(theta)*(ba1 - a1*g0) - cos(phi)*cos(psi)*cos(theta)*(ba3 - a3*g0) - cos(psi)*cos(theta)*sin(phi)*(ba2 - a2*g0), (cos(phi)*cos(psi) + sin(phi)*sin(psi)*sin(theta))*(ba2 - a2*g0) - (cos(psi)*sin(phi) - cos(phi)*sin(psi)*sin(theta))*(ba3 - a3*g0) + cos(theta)*sin(psi)*(ba1 - a1*g0), 0, 0, 0, 0, 0, 0, -cos(psi)*cos(theta),   cos(phi)*sin(psi) - cos(psi)*sin(phi)*sin(theta), - sin(phi)*sin(psi) - cos(phi)*cos(psi)*sin(theta),  0,                                 0,                                 0]
[  (cos(psi)*sin(phi) - cos(phi)*sin(psi)*sin(theta))*(ba2 - a2*g0) + (cos(phi)*cos(psi) + sin(phi)*sin(psi)*sin(theta))*(ba3 - a3*g0),                     sin(psi)*sin(theta)*(ba1 - a1*g0) - cos(phi)*cos(theta)*sin(psi)*(ba3 - a3*g0) - cos(theta)*sin(phi)*sin(psi)*(ba2 - a2*g0), (cos(phi)*sin(psi) - cos(psi)*sin(phi)*sin(theta))*(ba2 - a2*g0) - (sin(phi)*sin(psi) + cos(phi)*cos(psi)*sin(theta))*(ba3 - a3*g0) - cos(psi)*cos(theta)*(ba1 - a1*g0), 0, 0, 0, 0, 0, 0, -cos(theta)*sin(psi), - cos(phi)*cos(psi) - sin(phi)*sin(psi)*sin(theta),   cos(psi)*sin(phi) - cos(phi)*sin(psi)*sin(theta),  0,                                 0,                                 0]
[                                                                cos(theta)*sin(phi)*(ba3 - a3*g0) - cos(phi)*cos(theta)*(ba2 - a2*g0),                                                cos(theta)*(ba1 - a1*g0) + cos(phi)*sin(theta)*(ba3 - a3*g0) + sin(phi)*sin(theta)*(ba2 - a2*g0),                                                                                                                                                                       0, 0, 0, 0, 0, 0, 0,           sin(theta),                               -cos(theta)*sin(phi),                               -cos(phi)*cos(theta),  0,                                 0,                                 0]
[                                                                                                                                    0,                                                                                                                                               0,                                                                                                                                                                       0, 1, 0, 0, 0, 0, 0,                    0,                                                  0,                                                  0,  0,                                 0,                                 0]
[                                                                                                                                    0,                                                                                                                                               0,                                                                                                                                                                       0, 0, 1, 0, 0, 0, 0,                    0,                                                  0,                                                  0,  0,                                 0,                                 0]
[                                                                                                                                    0,                                                                                                                                               0,                                                                                                                                                                       0, 0, 0, 1, 0, 0, 0,                    0,                                                  0,                                                  0,  0,                                 0,                                 0]
[                                                                                                                                    0,                                                                                                                                               0,                                                                                                                                                                       0, 0, 0, 0, 0, 0, 0,                    0,                                                  0,                                                  0,  0,                                 0,                                 0]
[                                                                                                                                    0,                                                                                                                                               0,                                                                                                                                                                       0, 0, 0, 0, 0, 0, 0,                    0,                                                  0,                                                  0,  0,                                 0,                                 0]
[                                                                                                                                    0,                                                                                                                                               0,                                                                                                                                                                       0, 0, 0, 0, 0, 0, 0,                    0,                                                  0,                                                  0,  0,                                 0,                                 0]
[                                                                                                                                    0,                                                                                                                                               0,                                                                                                                                                                       0, 0, 0, 0, 0, 0, 0,                    0,                                                  0,                                                  0,  0,                                 0,                                 0]
[                                                                                                                                    0,                                                                                                                                               0,                                                                                                                                                                       0, 0, 0, 0, 0, 0, 0,                    0,                                                  0,                                                  0,  0,                                 0,                                 0]
[                                                                                                                                    0,                                                                                                                                               0,                                                                                                                                                                       0, 0, 0, 0, 0, 0, 0,                    0,                                                  0,                                                  0,  0,                                 0,                                 0]];
end